apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-app
  namespace: pranav-cicd

spec:
  replicas: 1

  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      imagePullSecrets:
        - name: nexus-secret

      containers:
      - name: flask-app

        image: registry.vforeseetech.com/my-repository/jenkins-cicd-automation:__IMAGE_TAG__
        imagePullPolicy: Always

        ports:
        - containerPort: 5000
